name: deploy-main  # 파이프라인 이름은 자유롭게 지어주세요

on:
  push:
    branches:
      - main  # main 브랜치에 새로운 커밋이 올라왔을 떄 실행되도록 합니다
  workflow_dispatch:  # 필요한 경우 수동으로 실행할 수도 있도록 합니다

jobs:
  deploy:
    runs-on: ubuntu-latest  # 운영체제 환경
    steps:
      # 1. GitHub 저장소의 코드를 가져옵니다
      - name: Checkout code
        uses: actions/checkout@v3